var mojicaLocalData = [
  {
    main_img_src: 'img/mojica_img/1.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/2.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/3.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/4.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/5.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/6.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/7.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/8.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/9.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/10.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/11.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/12.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/13.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/14.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/15.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/16.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/17.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/18.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/19.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/20.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/21.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/22.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/23.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/24.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/25.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/26.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/27.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/28.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/29.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/30.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/31.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
  {
    main_img_src: 'img/mojica_img/32.jpg',
    lrg_img_src: '',
    img_alt: '',
    description: 'this is a placeholder description',
    featured_items: '',
  },
];
